services:
  - type: web
    name: zenchat-server
    env: elixir
    buildCommand: "mix deps.get --only prod && mix compile"
    startCommand: "mix phx.server"
    envVars:
      - key: MIX_ENV
        value: prod
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: zenchat-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: zenchat-db
    plan: free
